name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Hello world Local action step
      id: hello
      uses: ./.github/actions/Docker-action
      with:
        who-to-greet: 'Mona the Octocat'
    
